### ISSUE TITLE
Source Run_occurrence_indicators_preprocessing.Rmd from the script in trias-project/Indicators repo.

### ISSUE THREAD

**Issue by soriadelva** [inbo/aspbo#109]
- [ ] In the run_occurrence_indicators_preprocessing.R script: instead of using the Run_occurrence_indicators_preprocessing.Rmd from the src folder, source the file directly from the Indicators repository within the trias project. As such, when this file is updated in the Indicators repo it will also be updated here. To this end, rewrite the following code, using a path of the type url = "https://raw.githubusercontent.com/trias-project/indicators/... instead of "src/05_occurrence_indicators_preprocessing.Rmd".
https://github.com/inbo/aspbo/blob/151d2f018577a76efc81dd5faa8b596352ffdb9b/src/run_occurrence_indicators_preprocessing.R#L18-L22

- [ ] If this is done and working, remove the Run_occurrence_indicators_preprocessing.Rmd file from the src folder.

**Comment by SanderDevisscher** [comment]
This script contains parts that are unique to the apsbo flows<sup>1</sup>. We could split the ".yaml" workflow into serial 4 steps (+runner setup). 

1. run R script that sources the .rmd directly from Trias. 
3. add logic to the R script that executes the parts unique to aspbo at the end of this script we should remove `df_ts`  and move the interim<sup>2</sup> files to the interim folder.
5. commit and push other changes
6. create pull request for interim files

`df_ts`, the export of the Trias rmd, will probably be to big (>100mb) for github and should therefor not be commited and pushed.

<sup>1</sup> see code below:
https://github.com/inbo/aspbo/blob/151d2f018577a76efc81dd5faa8b596352ffdb9b/src/05_occurrence_indicators_preprocessing.Rmd#L651-L685

<sup>2</sup>all files except `df_ts`
