### ISSUE TITLE
Update translations file

### ISSUE THREAD

**Issue by soriadelva** [inbo/aspbo#121]
## Write descriptions for:
- [x] ...

## Add the following ID's, with respective translations & descriptions:
- [x] createReport: Button to create a pdf report of a single species page 
- [x] occupancy: Generalised (intersected with a grid) area occupied by a species
- [ ] management3-countYearGroup: Management split per group
- [x] apply_gamObservations: Trias GAM based on observations
- [x] apply_gamOccupancy: Trias GAM based on occupancy

## Rework the translation of the following ID's:
- [x] global_indicators: Global indicators -> Checklist indicators

**Comment by SanderDevisscher** [comment]
URL for GRIIS checklist: https://www.gbif.org/dataset/6d9e952f-948c-4483-9807-575348147c7e

**Comment by SanderDevisscher** [comment]
The following ID's should be added to the translation file, with respective translations & descriptions:

- [x] createReport: Button to create a pdf report of a single species page (only ID)
- [x] occupancy: Generalised (intersected with a grid) area occupied by a species (ID +Description)
- [ ] management3-countYearGroup: Management split per group (ID + Description)
- [x] apply_gamObservations: Trias GAM based on observations (ID + Description)
- [x] apply_gamOccupancy: Trias GAM based on occupancy (ID + Description)

**Comment by SanderDevisscher** [comment]
@mvarewyck the alienspecies app flags amongst others these as not present in the translation file:
- [x] bottom
- [x] top
- [x] right
- [x] left
- [x] summarizeBy
- [x] 'S Gravenbrakel, Aalst, Aalter, ... 
- [x] t0
- [x] t1

I would suggest splitting the translation file into 2, namely:
1. translations: current translation file excluding part that should be in the other file 
2. translations_simple: translations for amongst others communes, provinces & regions and IDs needing only a translation and no description (this file would have only 4 fields: ID;EN;NL;FR)

What do you think ?

**Comment by mvarewyck** [comment]
@SanderDevisscher Sure, fine for me to split the file. 
Some remarks:
* Do we need to include translation for all municipalities? Or do I copy the original name and you update the ones you want?
* I try to keep track of the missing translations in this branch: https://github.com/inbo/aspbo/blob/mvarewyck-patch-1/data/output/UAT_direct/translations.csv
* I'll split the translations and perform according code updates after [this PR](https://github.com/inbo/alien-species-portal/pull/74)

**Comment by mvarewyck** [comment]
I have created 3 files for the translations:

* translations.csv: Columns for ID, title and description. Used for records that need to tie a description to the translated title (E.g. graphs in app)
* translations_simple.csv: Columns for ID and title. Simple translations in 3 languages (E.g. labels/choice options in app)
* translations_regions.csv: Columns for ID and title. Only for geographical regions (E.g. municipalities). Translations are not required for all 3 languages. If a translation is missing, the **dutch** translation is taken automatically. I have created a function which can create this file based on all regions used in the app [for reference](https://github.com/inbo/alien-species-portal/blob/fix_v1.1.0/alienSpecies/R/data_create.R#L543)

@soriadelva Do we need to document this somewhere?

**Comment by mvarewyck** [comment]
@soriadelva the translation files should be ready now to

- [x]  complete missing translations in [translations_simple.csv](https://github.com/inbo/aspbo/blob/121-update-translations-file/data/output/UAT_direct/translations_simple.csv) (indicated by TODO)
- [x] complete missing translations for the regions in [translations_regions.csv](https://github.com/inbo/aspbo/blob/121-update-translations-file/data/output/UAT_direct/translations_regions.csv). If translation is missing I now take the dutch one (title_nl).
- [x]  rework translations as requested above by Sander

**Comment by soriadelva** [comment]
> I have created 3 files for the translations:
> 
> * translations.csv: Columns for ID, title and description. Used for records that need to tie a description to the translated title (E.g. graphs in app)
> * translations_simple.csv: Columns for ID and title. Simple translations in 3 languages (E.g. labels/choice options in app)
> * translations_regions.csv: Columns for ID and title. Only for geographical regions (E.g. municipalities). Translations are not required for all 3 languages. If a translation is missing, the **dutch** translation is taken automatically. I have created a function which can create this file based on all regions used in the app [for reference](https://github.com/inbo/alien-species-portal/blob/fix_v1.1.0/alienSpecies/R/data_create.R#L543)
> 
> @soriadelva Do we need to document this somewhere?

@mvarewyck I will add this to the wiki under the information of the files in UAT_ direct 👌
