### ISSUE TITLE
add new vespawatch db dataflow

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#123]
When the new vespawatch db is ready w'll need to replace iasset part of the dataflow. 

1. [disable the iasset dataflow](https://github.com/inbo/aspbo/issues/122) 
2. work out the mapping for the new vespawatch db 
3. integrate the mapping into the existing automated dataflow
4. test the modified dataflow

**Comment by soriadelva** [comment]
This is done already in issue #124

**Comment by soriadelva** [comment]
I'll add more info after the PR is merged and the new version can be uploaded.

**Comment by SanderDevisscher** [comment]
@soriadelva this concerns the switch to the dataflow from the database (inclu. frontend) currently under construction to replace iAsset. What you are talking about is the modified flow from the iasset db (+gbif + old vespawatch db) 😉.

**Comment by soriadelva** [comment]
> @soriadelva this concerns the switch to the dataflow from the database (inclu. frontend) currently under construction to replace iAsset. What you are talking about is the modified flow from the iasset db (+gbif + old vespawatch db) 😉.

aaah 😅

**Comment by soriadelva** [comment]
> > @soriadelva this concerns the switch to the dataflow from the database (inclu. frontend) currently under construction to replace iAsset. What you are talking about is the modified flow from the iasset db (+gbif + old vespawatch db) 😉.
> 
> aaah 😅

Not fixed in 5 min unfortunately 😬

**Comment by SanderDevisscher** [comment]
> > > @soriadelva this concerns the switch to the dataflow from the database (inclu. frontend) currently under construction to replace iAsset. What you are talking about is the modified flow from the iasset db (+gbif + old vespawatch db) 😉.
> > 
> > 
> > aaah 😅
> 
> Not fixed in 5 min unfortunately 😬

nope 🤣
