### ISSUE TITLE
Modify code to build with GIT SHA

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#131]
@mvarewyck can you help me modify this code:

https://github.com/inbo/aspbo/blob/9c151007366b9ea960dbee722ca917f9a05932aa/src/build_docker_environment.Rmd#L39-L43

to build the app with GIT SHA info accessible ?

**Comment by mvarewyck** [comment]
It should include a build argument

`system(command = 'powershell "docker build  --build-arg GIT_SHA=$(git rev-parse HEAD) -t inbo/alienspecies ."')`

Documented [here](https://github.com/inbo/alien-species-portal/blob/fix_v1.0.0/README.md?plain=1#L25)
