### ISSUE TITLE
[BUG] something is wrong with commune assign for Vespa velutina

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#143]
There seems to be something off with the assigning of communes to the nests and observations of `Vespa velutina`
Going by the "All observations current year"
![image](https://github.com/inbo/aspbo/assets/16779320/0a3f8436-75d4-4144-9740-4fc91567c5cc)
One would expect most communes in east and west flanders to be at least lightly colored but instead they are mostly greyed out:
![image](https://github.com/inbo/aspbo/assets/16779320/868a04fa-0115-45dc-87b7-1a80573c7120)

We need to go step by step through the Vespa velutina flow to find what goes wrong & where. 

- [x] check whether [nesten.geojson](https://github.com/inbo/aspbo/blob/uat/data/output/UAT_processing/Vespa_velutina_shape/nesten.geojson) has realistic numbers of assigned communes: 373
- [x]  check whether [points.geojson](https://github.com/inbo/aspbo/blob/uat/data/output/UAT_processing/Vespa_velutina_shape/points.geojson) has realistic numbers of assigned communes: 31, it goes wrong here
- [ ] Check whether commune names form both files match with those in translation_region file

**Comment by soriadelva** [comment]
The issue occurs in the points.geojson file, and can be traced back to the fact that for the geographic information, the following columns level1Name, level2Name, and level3Name are stored. These columns originate from the dataset Vespa-Watch_gbif, which is the result of the get_data_from_gbif script. At first sight, it seems that the commune names are stored in level3Name but upon closer inspection, this column only contains 31 unique commune names, with villages and smaller cities typically being appointed to a larger city nearby. See example:

![Schermafbeelding 2024-05-15 190143](https://github.com/inbo/aspbo/assets/158742062/c93b37a7-b72c-43dc-a19b-f9c3baba43a4)

As a possible solution, we could use the gbif column municipality instead of level3Name, alternatively we could 
do an intersect with the communes.geojson and assign communes like that? @SanderDevisscher what do you think?

**Comment by SanderDevisscher** [comment]
@soriadelva is the municipality column filled in everytime ? I think we should do a intersect with the communes.geojson to test whether the municipality column can be considered correct. Is the info in the municipality column correct?

@mvarewyck which column do you use in the alienspecies portal ?

**Comment by mvarewyck** [comment]
> @mvarewyck which column do you use in the alienspecies portal ?

We're using `level3Name`. The column municipality is not available in [points.geojson](https://github.com/inbo/aspbo/blob/uat/data/output/UAT_processing/Vespa_velutina_shape/points.geojson)

```
{ "type": "Feature", "properties": { "eventDate": "2014-01-01T00:00:00Z", "year": 2014.0, "type": "Nest", "level1Name": "Vlaanderen", "level2Name": "Vlaams Brabant", "level3Name": "Leuven", "popup": "<a href= https://waarnemingen.be/observation/291142984 > Natuurpunt </a>", "inaturalist_ids": null, "gbif_ids": "4436546355", "institutionCode": "Natuurpunt" }, "geometry": { "type": "Point", "coordinates": [ 4.95079, 50.84324 ] } }
```

**Comment by SanderDevisscher** [comment]
@soriadelva we should overwrite level3Name with the content of municipality if this data is correct.

**Comment by soriadelva** [comment]
@SanderDevisscher ik ben klaar om dit te pushen en een PR te maken, maar had nog 1 vraagje ivm de vertalingen. De level1Name  (gewest) kolom van interimdata, de dataset die gebruikt wordt om een aantal csv's zoals zekere_nesten_waarnemingen en onzekere_nesten_waarnemingen te genereren, heeft momenteel als entries o.a., Vlaanderen, Wallonie, en Bruxelles. Ik zou dit veranderen naar de title_ids die in de translations file staan (flanders, wallonia, brussels) maar weet niet of dit op een andere plek problemen kan geven door bepaalde filters die ingesteld staan op de originele namen (bvb filter (level1Name==Vlaanderen,...).

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher ik ben klaar om dit te pushen en een PR te maken, maar had nog 1 vraagje ivm de vertalingen. De level1Name (gewest) kolom van interimdata, de dataset die gebruikt wordt om een aantal csv's zoals zekere_nesten_waarnemingen en onzekere_nesten_waarnemingen te genereren, heeft momenteel als entries o.a., Vlaanderen, Wallonie, en Bruxelles. Ik zou dit veranderen naar de title_ids die in de translations file staan (flanders, wallonia, brussels) maar weet niet of dit op een andere plek problemen kan geven door bepaalde filters die ingesteld staan op de originele namen (bvb filter (level1Name==Vlaanderen,...).

Dat gaat zeker issues geven maar we gaan ons daaraan moeten conformeren beter nu de korte pijn 😉 
Ik ben momenteel nog bezig met enkele aanpassingen te reviewen die @jrhillae gemaakt heeft aan hetzelfde script (zie #158). Vermoedelijk zal dit voor conflicten zorgen bij het mergen. Maar die lossen we wel op 😉

**Comment by soriadelva** [comment]
> > @SanderDevisscher ik ben klaar om dit te pushen en een PR te maken, maar had nog 1 vraagje ivm de vertalingen. De level1Name (gewest) kolom van interimdata, de dataset die gebruikt wordt om een aantal csv's zoals zekere_nesten_waarnemingen en onzekere_nesten_waarnemingen te genereren, heeft momenteel als entries o.a., Vlaanderen, Wallonie, en Bruxelles. Ik zou dit veranderen naar de title_ids die in de translations file staan (flanders, wallonia, brussels) maar weet niet of dit op een andere plek problemen kan geven door bepaalde filters die ingesteld staan op de originele namen (bvb filter (level1Name==Vlaanderen,...).
> 
> Dat gaat zeker issues geven maar we gaan ons daaraan moeten conformeren beter nu de korte pijn 😉 Ik ben momenteel nog bezig met enkele aanpassingen te reviewen die @jrhillae gemaakt heeft aan hetzelfde script (zie #158). Vermoedelijk zal dit voor conflicten zorgen bij het mergen. Maar die lossen we wel op 😉

Ok, top. Dan push ik en zal een PR aanmaken om te mergen met #121, zoals gisteren besproken 🙂

**Comment by jrhillae** [comment]
@SanderDevisscher, @soriadelva: een aantal nesten hebben gemeente en provincie 'onbekend' omdat ze bij rapporteren de default locatie aannamen en deze niet overschreven. Kan hier ook rekening mee worden gehouden dat deze niet worden overschreven? Gemma is momenteel van een aantal nesten nog de goede coördinaten aan het opzoeken. Dan pas ik de flow aan om deze erin toe te voegen.

**Comment by SanderDevisscher** [comment]
we zullen erop letten
