### ISSUE TITLE
Create species links file

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#165]
At species_information > more there is a subtab links. This subtab is currently empty. 

@mvarewyck How do we best populate it ? 

1. create a .csv under UAT_direct with gbiftaxonkey, url, link_text, description 
2. knit a pdf per species with taxonkey as filename and place it under UAT_direct 
3. knit a html per species with taxonkey as filename and place it under UAT_direct

**Comment by mvarewyck** [comment]
A knitted html file is the best option. It is more flexible in formatting the content than a csv file and is more convenient to include in a UI than a pdf.

Template file: [test.md](https://github.com/inbo/aspbo/files/15486782/test.md)
can be rendered using `rmarkdown::render("test.md")`

**Comment by mvarewyck** [comment]
Additional note: I don't think we even have to upload these files to the S3 bucket if they don't change too often.

Like we do for the trias risk maps, we can retrieve the data from GIT directly:
* [check which files are available](https://github.com/inbo/alien-species-portal/blob/fix_v1.0.0/alienSpecies/inst/app/global.R#L71)
* [retrieve a specific file from GIT](https://github.com/inbo/alien-species-portal/blob/fix_v1.0.0/alienSpecies/R/mapRaster.R#L137)

**Comment by SanderDevisscher** [comment]
@soriadelva will you create a example page for vespa velutina with:
- report a sigthing: https://waarnemingen.be/go/vespa-velutina/?
- vespa watch: https://www.vespawatch.be/

**Comment by soriadelva** [comment]
@mvarewyck we would like to have these HTML files in three languages (NL, EN, FR). What would be the best way to do that? Should I upload three different HTML files?

**Comment by SanderDevisscher** [comment]
@soriadelva can you also create a page for _Lithobates catesbeianus (2427091)_ 
some usefull links: 
- life project ivm beheer van stierkikker in Vlaanderen: https://www.natuurenbos.be/projecten/life-3n-stierkikker
- report a sigthing: https://waarnemingen.be/go/lithobates-catesbeianus/?showcase=1
- ecopedia page: https://www.ecopedia.be/dieren/amerikaanse-stierkikker

**Comment by mvarewyck** [comment]
> @mvarewyck we would like to have these HTML files in three languages (NL, EN, FR). What would be the best way to do that? Should I upload three different HTML files?

If the files share a lot of info, then it's better to keep everything in a single .Rmd file with a parameter for the language.
This will help you in the future so you don't have to update it in every language/file. 
Example file: [test.txt](https://github.com/user-attachments/files/15984657/test.txt)
1. Change the extension of the file to .Rmd
2. Render using `rmarkdown::render("test.Rmd")` default English or `rmarkdown::render("test.Rmd", params = list(language = "nl"))` for Dutch

**Comment by SanderDevisscher** [comment]
the ecopedia page should be included when available.
In case of aziatische hoornaar it is: https://www.ecopedia.be/dieren/aziatische-hoornaar

**Comment by mvarewyck** [comment]
@soriadelva Can you change the output format to `output: html_fragment` like my template? Otherwise there are warnings in the app because both the html and app define `<html><head><title><body>` etc. 

Another question: will there be a merge with `main` branch or should I retrieve the files from `uat` or `main` depending on where the app is deployed?

**Comment by SanderDevisscher** [comment]
> Another question: will there be a merge with `main` branch or should I retrieve the files from `uat` or `main` depending on where the app is deployed?

I think 'retrieving the files from `uat` or `main` depending on where the app is deployed' is the best solution. This keeps the testing step.
