### ISSUE TITLE
create a file to link with the Harmonia+ db

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#166]
The Harmonia+ db is a staple in risk assesement in Belgium and the exoten-portaal should be linked with this db. 

@mvarewyck what are the options here ? 

1. create a .csv with gbiftaxonkey & harmonia+ key and then add a link to the Harmonia+ page 
2. option 1 but embed the Harmonia+ page 

The Harmonia+ url for Acer negundo (3189866 on gbif) is https://ias.biodiversity.be/species/show/103 . The 103 seems to be the Harmonia+ key. 

@bramdhondt since you are closely involved with Harmonia+, is there a list of species currently on Harmonia+? Which we can use to link with the exotenportaal ?

**Comment by timadriaens** [comment]
actually this is the "harmonia information system key" (which refers to ISEIA assessments). There is no list as far as I know but of course the developer should be able to extract that (Nicolas Noé, nicolas[ad]niconoe.eu ).

there is the [supplements](http://www.reabic.net/journals/mbi/2015/Supplements/MBI_2015_Vanderhoeven_etal_Supplement.xls) to this [paper](https://purews.inbo.be/ws/portalfiles/portal/8919578/Vanderhoeven_etal_2015_ManagementBiologicalInvasions.pdf) which have the ISEIA scores but not the links to the pages on harmonia.

there is also the riparias target list in [this spreadsheet](https://docs.google.com/spreadsheets/d/15f17hXE9ZyUxEe2xA0seKs0CSibgYJdkaWcnmVoI1yY/edit#gid=0), it does have the links to the harmonia pages but only for the spp. relevant for RIPARIAS

**Comment by mvarewyck** [comment]
> @mvarewyck what are the options here ?
> 
> 1. create a .csv with gbiftaxonkey & harmonia+ key and then add a link to the Harmonia+ page
> 2. option 1 but embed the Harmonia+ page

I think it is best to include a link to the webpage. Option 2 is including it using an [`iframe`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) which is good for small bits but for a whole webpage often results in weird rescaling and being sloppy.

For creating the csv file, it's always best if this could be done 'at the source', especially for future updates. I try to keep away from web scraping. That said, I don't see any gbiftaxonkey included in the table source code on the webpage, so we might have to go via the scientific name.

**Comment by SanderDevisscher** [comment]
We could create a csv list of taxonkey harmonia+ key combo's and some logic to flag taxonkeys and/or harmonia+ keys without combination. This would result into an big initial load.

**Comment by soriadelva** [comment]
@mvarewyck I am currently making this .csv file with the columns scientific_name, gbif_taxonkey, harmonia_key, and harmonia_url. Is there any other information you would need there and where should I best store this file?

**Comment by mvarewyck** [comment]
> @mvarewyck I am currently making this .csv file with the columns scientific_name, gbif_taxonkey, harmonia_key, and harmonia_url. Is there any other information you would need there and where should I best store this file?

That information is sufficient. I think you best store it [here](https://github.com/inbo/aspbo/tree/uat/data/output/UAT_direct), then it will automatically be uploaded to the S3 buckets - no need to update any script there.

**Comment by mvarewyck** [comment]
@soriadelva For the record, I have checked which harmonia records could be linked to the records in alien species portal. Only 2 are not present, but they are expected if I check on harmonia. 

```
    harmoniaData <- readS3(read.csv, sep = ";", encoding = "UTF-8", file = "harmonia_info.csv")
    missingIds <- which(!harmoniaData$gbif_taxonkey %in% exotenData$nubKey)
    
    harmoniaData[missingIds, ]
    #                harmonia_name                         scientificName
    # 24 Carpobrotus acinaciformis Carpobrotus acinaciformis (L.) L.Bolus
    # 79         Perccottus glenii       Perccottus glenii Dybowski, 1877
    #    gbif_taxonkey harmonia_key                                 harmonia_url
    # 24       3703606          118 https://ias.biodiversity.be/species/show/118
    # 79       2390064           82  https://ias.biodiversity.be/species/show/82
```

**Comment by soriadelva** [comment]
> @soriadelva For the record, I have checked which harmonia records could be linked to the records in alien species portal. Only 2 are not present, but they are expected if I check on harmonia.
> 
> ```
>     harmoniaData <- readS3(read.csv, sep = ";", encoding = "UTF-8", file = "harmonia_info.csv")
>     missingIds <- which(!harmoniaData$gbif_taxonkey %in% exotenData$nubKey)
>     
>     harmoniaData[missingIds, ]
>     #                harmonia_name                         scientificName
>     # 24 Carpobrotus acinaciformis Carpobrotus acinaciformis (L.) L.Bolus
>     # 79         Perccottus glenii       Perccottus glenii Dybowski, 1877
>     #    gbif_taxonkey harmonia_key                                 harmonia_url
>     # 24       3703606          118 https://ias.biodiversity.be/species/show/118
>     # 79       2390064           82  https://ias.biodiversity.be/species/show/82
> ```

@mvarewyck, thanks for checking! I searched these species on GBIF and it seems that they have not been reported in Belgium yet, even though they are expected to have a high establishment potential here.

**Comment by b-dhondt** [comment]
Note that their absence is also reflected in their Harmonia score: "A0", or "absent from Belgium".
