### ISSUE TITLE
Upload all translation files to uat

### ISSUE THREAD

**Issue by mvarewyck** [inbo/aspbo#167]
Update the [upload_direct_to_UAT script](https://github.com/inbo/aspbo/blob/uat/src/upload_direct_to_UAT.R#L39) such that all translation files are now uploaded to uat: translations.csv; translations_simple.csv; translations_regions.csv

**Comment by mvarewyck** [comment]
These changes are available in [branch 153-test-*](https://github.com/inbo/aspbo/tree/153-test-httpsgithubcominboalien-species-portalpull74)
@SanderDevisscher Do you plan to create a PR for this branch?

**Comment by SanderDevisscher** [comment]
Not really since the intention of the branch was just testing the fixv1.0.0 pr.
