### ISSUE TITLE
Rework active hotbeds calculation

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#174]
The active hotbeds map should display a hot map of recent (last 2 weeks) observations independent of management status of nearby nests. This should occur at a high update frequency to allow for rapid response. 

these are the steps that are needed to achieve this according to me:
- [ ] Create a new workflow<sup>1</sup>
- [ ] fix https://github.com/inbo/vespaR/issues/173
- [ ] write script to get recent observations<sup>2</sup> from [waarnemingenAPI](https://docs.google.com/spreadsheets/d/1gVrPeMj74pDkHd5oQJ8fmlMRAP5Dh85SManUzLI1eJQ/edit?gid=0#gid=0) - gsheet
- [ ] export directly to the uat-bucket<sup>3</sup> & in longer term to the prd bucket<sup>4</sup>

<sup>1</sup> this workflow should have the following elements:
- [ ] daily CRON trigger: '0 2 * * *'
- [ ] gsheet_token: ${{ secrets.gsheet_token }}
- [ ] GITHUB_TOKEN: ${{ secrets.AUTOMATISATION }}
- [ ] a [Assume Role](https://github.com/inbo/aspbo/blob/c13ea9811fccece49f978aae36eddf1827731e43/.github/workflows/update_indicators_preprocessing.yaml#L69C15-L78) step

<sup>2</sup> if I understand correctly this can be achieved by reversing the activity filter ea `filter(!activity %in% c(3240,3036))`. @jrhillae is this correct ? 

<sup>3</sup> @mvarewyck  given the high frequency (daily) I would like to bypass the review step. What should be the filename of the file on the bucket ? I assume there are some changes required on the app side as well they should be listed at https://github.com/inbo/aspbo/issues/219.

<sup>4</sup> @TheJenne18 is it possible in current setup to bypass the UAT bucket step and update files on the PRD bucket directly ? Given the high frequency of updates (daily) I don't think going through 2 validation steps is viable 🤔

**Comment by SanderDevisscher** [comment]
> 3 @mvarewyck given the high frequency (daily) I would like to bypass the review step. What should be the filename of the file on the bucket ? I assume there are some changes required on the app side as well they should be listed at #219.

The file should be named `actieve_haarden.geojson` => current [actieve_haarden.geojson](https://github.com/inbo/aspbo/blob/uat/data/output/UAT_processing/Vespa_velutina_shape/actieve_haarden.geojson) should be removed.

**Comment by SanderDevisscher** [comment]
> 4 @TheJenne18 is it possible in current setup to bypass the UAT bucket step and update files on the PRD bucket directly ? Given the high frequency of updates (daily) I don't think going through 2 validation steps is viable 🤔

@TheJenne18 can you confirm the PRD bucket exists ?

**Comment by mvarewyck** [comment]
> @TheJenne18 can you confirm the PRD bucket exists ?

Yes I have access to it.
