### ISSUE TITLE
NL and FR HTML files for Stierkikker show problems when rendering special signs (e.g., é, ë,...)

### ISSUE THREAD

**Issue by soriadelva** [inbo/aspbo#205]
See example:
![example](https://github.com/inbo/aspbo/assets/158742062/b686e1a2-2713-4ffe-88de-8366d16b4141)
@mvarewyck any thoughts what could go wrong here? It doesn't occur when I knit the .Rmd files in Rstudio and also the Vespa velutina files don't show any problems even though they are constructed with the same code and include the same characters such as é and ë. I checked if the encoding was UTF-8 but that didn't seem to be the issue. When I convert back to html_document instead of html_fragment there is also no issue.

**Comment by mvarewyck** [comment]
It's due to the fact that html_fragment has no `<head>` which defines the encoding e.g. Latin-1 or UTF-8 so your browser will guess. Probably depends on the browser whether it will guess correctly and thus render the special characters correctly. I would not worry about this, as it is defined correctly when included in the app.

![Screenshot from 2024-07-04 15-19-35](https://github.com/inbo/aspbo/assets/22143743/cabd9546-3adc-4788-ada7-4c8eddd53639)

**Comment by soriadelva** [comment]
> It's due to the fact that html_fragment has no `<head>` which defines the encoding e.g. Latin-1 or UTF-8 so your browser will guess. Probably depends on the browser whether it will guess correctly and thus render the special characters correctly. I would not worry about this, as it is defined correctly when included in the app.
> 
> ![Screenshot from 2024-07-04 15-19-35](https://private-user-images.githubusercontent.com/22143743/345844893-cabd9546-3adc-4788-ada7-4c8eddd53639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTk1MzUsIm5iZiI6MTcyMDA5OTIzNSwicGF0aCI6Ii8yMjE0Mzc0My8zNDU4NDQ4OTMtY2FiZDk1NDYtM2FkYy00Nzg4LWFkYTctNGM4ZWRkZDUzNjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEzMjAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZjE4Y2M4MDFlNjEwY2Q0MjZhMmE2MjU5MWNhNjc4N2UzNDExMGIxN2UwNjhjZTgzYTZlOTU0ZTc0YWMxNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.COFISkgdebF65RwCJ7PECcUdLpjeQQv4hf4D1_emnWY)

Okay, that's good news, thanks!
