### ISSUE TITLE
Missing columns for `be_alientaxa_cube_processed.parquet`

### ISSUE THREAD

**Issue by mvarewyck** [inbo/aspbo#252]
Given [this script](https://github.com/inbo/aspbo/blob/uat/src/cube_preprocessing.Rmd#L161), the file `be_alientaxa_cube_processed.parquet` on the bucket should contain extra columns `isFlanders,isWallonia,isBrussels,gemeente,provincie,gewest`.
However when I load the data, I don't get these (anymore):

```
> library(alienSpecies)
> tmpData <- loadTabularData(type = "occurrence")
occurrence data: 38940 observaties dateren van voor 1950 en zijn dus uitgesloten
> colnames(tmpData)
[1] "year"           "cell_code1"     "taxonKey"       "n"             
[5] "scientificName" "classKey"       "cell_code10"   
```

The file seems to be changed early september:

```
> tmpTable <- aws.s3::get_bucket_df(
      bucket = config::get("bucket", file = system.file("config.yml", package = "alienSpecies")))
> tmpTable[grep("cube", tmpTable$Key), ]
                                  Key             LastModified
7               be_alientaxa_cube.csv 2023-10-11T19:49:50.000Z
8   be_alientaxa_cube_processed.RData 2024-07-19T08:58:44.000Z
9 be_alientaxa_cube_processed.parquet 2024-09-03T08:29:44.000Z
```

@soriadelva Can we try to run the script again to see whether it still applies for the latest scripts/data?

Note: The file `be_alientaxa_cube_processed.RData` does contain all the extra columns. So the script might have been run on an old version of the R package `alienSpecies`?

```
> readS3(file = "be_alientaxa_cube_processed.RData")
> colnames(rawData)
 [1] "year"           "cell_code1"     "taxonKey"       "n"             
 [5] "isFlanders"     "isWallonia"     "isBrussels"     "gemeente"      
 [9] "provincie"      "gewest"         "scientificName" "classKey"      
[13] "cell_code10"   
```

**Comment by SanderDevisscher** [comment]
@mvarewyck the cube_preprocessing flow is running see https://github.com/inbo/aspbo/actions/runs/11071601429

**Comment by mvarewyck** [comment]
Thanks @SanderDevisscher 
Looks perfect now!

**Comment by mvarewyck** [comment]
It seems we're back to off.
The data has been updated on October 1st and necessary columns are missing again.
Not sure why it is going wrong.. is it overwritten accidentally in another script?

```
> tmpTable[grepl("cube", tmpTable$Key), ]
                                  Key             LastModified
7               be_alientaxa_cube.csv 2023-10-11T19:49:50.000Z
8   be_alientaxa_cube_processed.RData 2024-07-19T08:58:44.000Z
9 be_alientaxa_cube_processed.parquet 2024-10-01T08:53:59.000Z
```

**Comment by mvarewyck** [comment]
It was still in another script. Hope this fixes it :crossed_fingers:
