### ISSUE TITLE
Complete upload_files_to_UAT.R

### ISSUE THREAD

**Issue by Yingjie-ZhangOA** [inbo/aspbo#31]
Include 

- [ ]  raw data in `./data/input` folder,  `translation.csv` is located in `./data/ui`

- [ ] test existence of the raw data

- [ ] process raw data and put on bucket 

- [ ] test data files on bucket

**Comment by SanderDevisscher** [comment]
> Include
> 
> * [ ]   raw data in `./data/input` folder,  `translation.csv` is located in `./data/ui`

@Yingjie-ZhangOA the files you placed `./data/input`  are actually the results of processes from this and other repos. The flow I first envisioned was that we place the subset of these files that need no extra processing into `./data/output/` this then triggers an github action uploading the files. Maybe we need to split this flow into 2, (1) files that need **no extra processing** are placed in `./data/output/UAT_direct/` & (2) files that need **processing** are placed into `./data/output/UAT_processing/`. Changes to these folders trigger their respective github action. 

Things to do:
- [ ] @Yingjie-ZhangOA moves the files added to `./data/input` to their resp. folders in `./data/output/`
- [ ] @Yingjie-ZhangOA creates a new R script to handle files needing processing 
- [ ] @SanderDevisscher changes github action trigger to changes in `./data/output/UAT_direct/`
- [ ] @Yingjie-ZhangOA @SanderDevisscher create github action triggered by changes to `./data/output/UAT_processing/`

> * [ ]  test existence of the raw data
> * [ ]  process raw data and put on bucket
> * [ ]  test data files on bucket

**Comment by Yingjie-ZhangOA** [comment]
@SanderDevisscher  Thanks for the explanation, can you confirm the following?

In that case, we will need two R scripts that respond to event triggered by changes coming from`./data/output/UAT_direct/` and `./data/output/UAT_processing/` respectively (demonstrated below).
<img width="651" alt="Screenshot 2023-11-13 at 10 36 27" src="https://github.com/inbo/aspbo/assets/50108790/b6f0acf7-b0dc-45d7-b87a-50ea261c418e">

* As for the `.geojson` files currently in `./data/spatial/`, they should also be moved to `./data/output/UAT_processing/` because in the application we use the processed `.RData`.

* `./data/ui/translations.csv` should be moved to `./data/output/UAT_direct/` as well

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Thanks for the explanation, can you confirm the following?
> 
> In that case, we will need two R scripts that respond to event triggered by changes coming from`./data/output/UAT_direct/` and `./data/output/UAT_processing/` respectively (demonstrated below). <img alt="Screenshot 2023-11-13 at 10 36 27" width="651" src="https://user-images.githubusercontent.com/50108790/282421051-b6f0acf7-b0dc-45d7-b87a-50ea261c418e.png">

correct
> 
> * As for the `.geojson` files currently in `./data/spatial/`, they should also be moved to `./data/output/UAT_processing/` because in the application we use the processed `.RData`.
Correct.
This means I'll need to change the paths in scripts working with those files, see:

- [ ] https://github.com/inbo/aspbo/blob/d5b041bfb4359348d39cb9c2ec9c27c5abf0f81d/src/create_geojsons.Rmd#L41
- [ ] https://github.com/inbo/aspbo/blob/d5b041bfb4359348d39cb9c2ec9c27c5abf0f81d/src/create_geojsons.Rmd#L83
- [ ] https://github.com/inbo/aspbo/blob/d5b041bfb4359348d39cb9c2ec9c27c5abf0f81d/src/management_prep.Rmd#L199
- [ ] https://github.com/inbo/aspbo/blob/d5b041bfb4359348d39cb9c2ec9c27c5abf0f81d/src/management_prep.Rmd#L201
- [ ] https://github.com/inbo/aspbo/blob/d5b041bfb4359348d39cb9c2ec9c27c5abf0f81d/src/management_graphs.Rmd#L132
 
> * `./data/ui/translations.csv` should be moved to `./data/output/UAT_direct/` as well

correct

**Comment by Yingjie-ZhangOA** [comment]
commit f4ac68b 

* This is implemented, directory names and file names are used exactly the same as in the demonstration

<img alt="Screenshot 2023-11-13 at 10 36 27" width="651" src="https://user-images.githubusercontent.com/50108790/282421051-b6f0acf7-b0dc-45d7-b87a-50ea261c418e.png">

* I am not exactly sure the purpose of `upload_files_to_UAT.R`, do you want change made to  `UAT_filelist.csv` trigger action to put all the files listed there on bucket? or just to direct upload as we did in ` upload_direct_to_UAT.R`?  If the purpose is the latter, I think we can combine these two scripts.

**Comment by SanderDevisscher** [comment]
> commit [f4ac68b](https://github.com/inbo/aspbo/commit/f4ac68b41a5e1f9f4c76d86b6ba7957e7975213a)
> 
> * This is implemented, directory names and file names are used exactly the same as in the demonstration
> 
> <img alt="Screenshot 2023-11-13 at 10 36 27" width="651" src="https://user-images.githubusercontent.com/50108790/282421051-b6f0acf7-b0dc-45d7-b87a-50ea261c418e.png">
> 
> * I am not exactly sure the purpose of `upload_files_to_UAT.R`, do you want change made to  `UAT_filelist.csv` trigger action to put all the files listed there on bucket? or just to direct upload as we did in ` upload_direct_to_UAT.R`?  If the purpose is the latter, I think we can combine these two scripts.

`upload_files_to_UAT.R` was written to trigger an upload of the files on the filelist to the bucket. However given the current setup I think it is better to switch to a upload of all files from UAT_direct when any of these files is changed. 
So I think it should be more the latter.

**Comment by SanderDevisscher** [comment]
@Yingjie-ZhangOA wouldn't it be better to reduce these list into 1 list to make sure they contain the same files?  https://github.com/inbo/aspbo/blob/f4ac68b41a5e1f9f4c76d86b6ba7957e7975213a/src/upload_direct_to_UAT.R#L32
https://github.com/inbo/aspbo/blob/f4ac68b41a5e1f9f4c76d86b6ba7957e7975213a/src/upload_direct_to_UAT.R#L47
