### ISSUE TITLE
create_timeseries fails with 404

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#36]
https://github.com/inbo/aspbo/actions/workflows/update_indicators_preprocessing.yaml fails with 404 - error

After investigation I found out the Trias `be_classes_cube.csv` was moved or deleted all together (see https://github.com/trias-project/occ-cube-alien/issues/43). This is most likely the cause of the failure. 

when an alternative source has been identified it should be inserted here:
https://github.com/inbo/aspbo/blob/fa0c02a59542f1f812658a26504f7e219d148286/src/05_occurrence_indicators_preprocessing.Rmd#L88

the workflow should be reactivated as well

**Comment by SanderDevisscher** [comment]
The [update_indicators_preprocessing](https://github.com/inbo/aspbo/blob/uat/.github/workflows/update_indicators_preprocessing.yaml) - workflow should be reworked into the following steps. 

1. retrieve the needed data from zenodo (https://zenodo.org/records/10058400) 
2. store the data on the uat bucket 
3. retrieve the data from there
4. do processing
5. store result directly on bucket

Maybe these steps should be conditional jobs like the [get_griis_checklist](https://github.com/inbo/aspbo/blob/uat/.github/workflows/get_griis_checklist.yaml)  - workflow?

**Comment by mvarewyck** [comment]
The timeseries data we need are not on Zenodo and also not tracked in the GIT of [Trias project](https://github.com/trias-project/indicators/blob/main/src/05_occurrence_indicators_preprocessing.Rmd#L41). They are a result of this script https://github.com/trias-project/indicators/blob/main/src/05_occurrence_indicators_preprocessing.Rmd

@SanderDevisscher So I think you could 

1. Execute this script https://github.com/trias-project/indicators/blob/main/src/05_occurrence_indicators_preprocessing.Rmd
2. do processing on the resulting data from [`here::here("data", "interim", "df_timeseries.tsv")`](https://github.com/trias-project/indicators/blob/main/src/05_occurrence_indicators_preprocessing.Rmd#L655C18-L655C70)
3. store result directly on bucket

Questions/Remarks
* Wrt step 2: The path where the resulting data from the trias script is stored, is hard-coded and I don't know how easily this file can be accessed in a github action. You might need to copy it from the original location to a temporary folder and point the processing function to that path.
* In the Trias script there are some input data files which are retrieved from the GIT repos, although they are also available on Zenodo. You might want to use the version from Zenodo. 
  - https://github.com/trias-project/indicators/blob/main/src/05_occurrence_indicators_preprocessing.Rmd#L68
  - https://github.com/trias-project/indicators/blob/main/src/05_occurrence_indicators_preprocessing.Rmd#L112

**Comment by SanderDevisscher** [comment]
@mvarewyck I've allready made a modified version of [05_occurrence_indicators_preprocessing.Rmd](https://github.com/inbo/aspbo/blob/uat/src/05_occurrence_indicators_preprocessing.Rmd) which fetches the zenodo files. 

Other paths might need to be changed for example the intermediate step should be stored on the bucket as well.
Also these lines might need a fresh look: 
https://github.com/inbo/aspbo/blob/2a3a97c5a03a122921bec27e6f77719531ae22cd/src/run_createTimeseries.R#L8-L10

**Comment by SanderDevisscher** [comment]
some more relevant info: https://github.com/inbo/aspbo/blob/uat/.github/PR_occ_indic_preprocessing.md

**Comment by mvarewyck** [comment]
@SanderDevisscher Thanks, that clarifies. I think we need following modifications:

* Write output to S3 bucket for https://github.com/inbo/aspbo/blob/uat/src/05_occurrence_indicators_preprocessing.Rmd#L635-L640
* Update the function `alienSpecies::createTimeseries()` such that it can read input data from the bucket directly
* Remove these lines (redundant) https://github.com/inbo/aspbo/blob/uat/src/run_createTimeseries.R#L6-L10

I'll do that and create a PR

**Comment by mvarewyck** [comment]
I couldn't test the new pipeline. The processing script fails for me [here](https://github.com/inbo/aspbo/blob/uat/src/05_occurrence_indicators_preprocessing.Rmd#L330-L345) with error:
```
46/94 [extract_x_y_baseline]                     

Quitting from lines 331-345 [extract_x_y_baseline] (05_occurrence_indicators_preprocessing.Rmd)
Error in `tibble()` at tidylog/R/mutate.R:8:4:
! Tibble columns must have compatible sizes.
• Size 49146: Existing data.
• Size 49147: Column `y`.
ℹ Only values of size one are recycled.
Backtrace:
 1. df_bl %>% distinct(eea_cell_code) %>% ...
 7. tibble::tibble(...)
      at tidylog/R/mutate.R:8:4
```      
So, for now I copied a local version of the `df_timeseries.RData` to the S3 bucket.
