### ISSUE TITLE
write muskrat data prep scripts

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#5]
>@mvarewyck I'll write a script to extract the neccessary data from gbif and provide you with some cleaned datasets to use.

_Originally posted by @SanderDevisscher in https://github.com/inbo/alien-species-portal/issues/50#issuecomment-1683929695_

**Comment by SanderDevisscher** [comment]
@EmmaCartuyvels1 what is the update frequency for these datasets ?

**Comment by SanderDevisscher** [comment]
> @EmmaCartuyvels1 what is the update frequency for these datasets ?

wekelijks

**Comment by SanderDevisscher** [comment]
`0 0 * 1-12 1`

**Comment by SanderDevisscher** [comment]
@mvarewyck @Yingjie-ZhangOA which columns from `./data/output/UAT_direct/Ondatra_zibethicus.csv` do you need/use ?

The example data contains only 1000 rows of data while the full dataset contains 125196. This results in a file 170mb in size (too large for github). dropping most of the unnecessary columns will potentially reduce the size significantly.

**Comment by mvarewyck** [comment]
See here: https://github.com/inbo/alien-species-portal/issues/50#issuecomment-1765136697

We definitely need
* year
* individualCount
* NAAM
* provincie
* GEWEST -> currently missing

Nice to keep, but currently not used:

- gbifID
- decimalLatitude
- decimalLongitude

**Comment by SanderDevisscher** [comment]
thanks 😅
