### ISSUE TITLE
Write Oxyura jamaicensis dataflow

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#53]
Input: https://www.gbif.org/dataset/7522721f-4d97-4984-8231-c9e061ef46df
Output: https://github.com/inbo/aspbo/blob/uat/data/output/UAT_direct/Oxyura_jamaicensis.csv
Trigger: cron: '0 0 1 1-12 *' (= “At 00:00 on day-of-month 1 in January through december.”) & workflow_dispatch:

- [ ] create 'update_oxyura_jamaicensis_management.R'
- [ ] create 'install_packages_oxyura_jamaicensis.R'
- [ ] create 'update_oxyura_jamaicensis_management.yaml'
- [ ] create 'PR_update_oxyura_jamaicensis_management.md'

@DimEvil Is it possible to automate the flow from recorder to gbif to make sure it gets updated at least yearly ? 
Same question for the flow from sk_analyse to gbif ? Update frequency may be higher if not an issue!

**Comment by DimEvil** [comment]
Ruddy duck will be monthly updated, automatically. 
SK analyse is unsure. will investigate

**Comment by DimEvil** [comment]
SK analyse --> automatic publication flow now (weekly update)
Oxyura --> automatic publication flow now (monthly update)
Muntiacus --> automatic publication flow now (monthly update)

**Comment by SanderDevisscher** [comment]
check whether communes & provinces are added
