### ISSUE TITLE
[BUG] column habitat is missing from GRIIS checklist

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#55]
https://github.com/inbo/alien-species-portal/issues/66#issuecomment-1847282344

**Comment by SanderDevisscher** [comment]
It appears more than habitat is missing from the name_usage download of the GRIIS checklist. 

I've had to change the workflow to include a manual download of the GRIIS dwca from gbif.

some further mapping is also needed concerning the degree of establishment. 

<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky">category</th>
    <th class="tg-0pky">definition</th>
    <th class="tg-0pky">Proposed label and controlled value string</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky">A</td>
    <td class="tg-0pky">Not transported beyond limits of native range</td>
    <td class="tg-0pky">native</td>
  </tr>
  <tr>
    <td class="tg-0pky">B1</td>
    <td class="tg-0pky">Individuals in captivity or quarantine (i.e. individuals provided with conditions suitable for them, but explicit measures of containment are in place)</td>
    <td class="tg-0pky">captive</td>
  </tr>
  <tr>
    <td class="tg-0pky">B2</td>
    <td class="tg-0pky">Individuals in cultivation (i.e. individuals provided with conditions suitable for them, but explicit measures to prevent dispersal are limited at best)</td>
    <td class="tg-0pky">cultivated</td>
  </tr>
  <tr>
    <td class="tg-0pky">B3</td>
    <td class="tg-0pky">Individuals directly released into novel environment</td>
    <td class="tg-0pky">released</td>
  </tr>
  <tr>
    <td class="tg-0pky">C0</td>
    <td class="tg-0pky">Individuals released outside of captivity or cultivation in a location, but incapable of surviving for a significant period</td>
    <td class="tg-0pky">failing</td>
  </tr>
  <tr>
    <td class="tg-0pky">C1</td>
    <td class="tg-0pky">Individuals surviving outside of captivity or cultivation in a location, no reproduction</td>
    <td class="tg-0pky">casual</td>
  </tr>
  <tr>
    <td class="tg-0pky">C2</td>
    <td class="tg-0pky">Individuals surviving outside of captivity or cultivation in a location, reproduction is occurring, but population not self-sustaining</td>
    <td class="tg-0pky">reproducing</td>
  </tr>
  <tr>
    <td class="tg-0pky">C3</td>
    <td class="tg-0pky">Individuals surviving outside of captivity or cultivation in a location, reproduction occurring, and population self-sustaining</td>
    <td class="tg-0pky">established</td>
  </tr>
  <tr>
    <td class="tg-0pky">D1</td>
    <td class="tg-0pky">Self-sustaining population outside of captivity or cultivation, with individuals surviving a significant distance from the original point of introduction</td>
    <td class="tg-0pky">colonising</td>
  </tr>
  <tr>
    <td class="tg-0pky">D2</td>
    <td class="tg-0pky">Self-sustaining population outside of captivity or cultivation, with individuals surviving and reproducing a significant distance from the original point of introduction</td>
    <td class="tg-0pky">invasive</td>
  </tr>
  <tr>
    <td class="tg-0pky">E</td>
    <td class="tg-0pky">Fully invasive species, with individuals dispersing, surviving and reproducing at multiple sites across a greater or lesser spectrum of habitats and extent of occurrence</td>
    <td class="tg-0pky">widespreadInvasive</td>
  </tr>
</tbody>
</table>

from [Improving Darwin Core for research and management of alien species](https://biss.pensoft.net/article/38084/) based on [Blackburn et al. (2011)](https://doi.org/10.1016/j.tree.2011.03.023)

**Comment by timadriaens** [comment]
@SanderDevisscher the thing is that the individual checklists still have to be adapted to the new standard to include these fields. We are doing that at GRIIS hackathon days with @damianooldoni @peterdesmet . If you are interested...

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher the thing is that the individual checklists still have to be adapted to the new standard to include these fields. We are doing that at GRIIS hackathon days with @damianooldoni @peterdesmet . If you are interested...

Ja graag, wanneer en waar ?

**Comment by peterdesmet** [comment]
The hackathon was last Wednesday (December 15), but we'll have to organize several more to finish the work.

**Comment by SanderDevisscher** [comment]
I'm interested in the next hackathon(s) ;-)

**Comment by SanderDevisscher** [comment]
@timadriaens while waiting for the continuation of the hackathons I'll have to do a mapping of native ranges, habitats & degree of establishment. 
Currently these classes of degree of establishment can be found in the description.txt from gbif: 

```
table(degree_of_establishment$description)

        blackburn_et_al_2011:B2         blackburn_et_al_2011:B3         blackburn_et_al_2011:C0 
                              5                               1                               6 
        blackburn_et_al_2011:C3         blackburn_et_al_2011:D2          blackburn_et_al_2011:E 
                              3                               1                              13 
    captive (blackburn_2011:B1)                          casual      casual (blackburn_2011:C1) 
                              1                            2028                              11 
                     colonizing  colonizing (blackburn_2011:D1)                     established 
                              2                               1                             780 
established (blackburn_2011:C3)                         extinct                      introduced 
                              4                              19                             170 
                       invasive    released (blackburn_2011:B3) reproducing (blackburn_2011:C2) 
                              1                              28                               5 
```

for most classes I can make direct mapping based on the table from blackburn (https://github.com/inbo/aspbo/issues/55#issuecomment-1858046675) however this is not the case with `introduced`. Can I say `introduced` is the same as `released` ? or should I add an extra class `introduced` ? I'll implement the latter for now. I'll also add a class extinct.

**Comment by timadriaens** [comment]
native ranges have imo already been mapped with @peterdesmet

**Comment by SanderDevisscher** [comment]
> native ranges have imo already been mapped with @peterdesmet

Correct, but the output of rgbif function I'm supposed to use (`name_usage()`) to download the checklist doesn't include all this info so I need to recombine this export with data from a manually downloaded dwca that does. Also for the app the blackburn class is less relevant so this needs some mapping.

**Comment by damianooldoni** [comment]
Hi! No, you can do it with rgbif! I do it in preprocessing pipeline for checklist TriAS indicators. Check
https://trias-project.github.io/indicators/01_get_data_input_checklist_indicators.html#2_Get_data where I first get the taxonomic core and then I do a loop  (via purrr function `map_dfr()`) to get both distribution and description extensions. In description you have the native range. 
I think you can entirely reuse the code in this pipeline to automatise the production of the "tidy" data.frame I save at the end of the pipeline: `data_input_checklist_indicators.tsv`.

To avoid copy-paste from my Rmd to your R script in this repo, notice you can run all R code chunks contained in a Rmd via knitr package:

```r
library(knitr)

# create temporary R file
tempR <- tempfile(fileext = ".R")
knitr::purl("https://raw.githubusercontent.com/trias-project/indicators/main/src/01_get_data_input_checklist_indicators.Rmd", output=tempR)
source(tempR)
unlink(tempR)
```
