### ISSUE TITLE
Expand wiki

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#64]
- [x] add workflows
- [ ] add rationale
- [ ] ...

**Comment by SanderDevisscher** [comment]
https://app.diagrams.net/#G1NwvxXZdCdrZJKOMSJwTsJ2IPBNc7Xz7_

**Comment by SanderDevisscher** [comment]
@soriadelva feel free to add some of your notes to the wiki.

**Comment by soriadelva** [comment]
> @soriadelva feel free to add some of your notes to the wiki.

The draw.io diagrams are updated. I suggest we merge this branch so they are also updated on the uat. From there I can add the new versions to the wiki and update the text.
