### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by mvarewyck** [inbo/aspbo#76]
I have added some extra entries at the bottom of the file (see TODO) wrt Vespa Velutina management, branch mvarewyck-patch-1
@bramdhondt Could you please complete [here](https://github.com/inbo/aspbo/blob/mvarewyck-patch-1/data/output/UAT_direct/translations.csv)?

**Comment by b-dhondt** [comment]
@mvarewyck : ik heb een kopij van _translations.csv_ gemaakt, _translations_v24-02-13.csv_ genoemd, alle TODO's opgelost (plus nog wat kleinigheden verbeterd), en gepusht.

Ik beschouw je vraag daarmee als afgehandeld.
